/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package procurement_management.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shahab
 */
public class Users extends javax.swing.JFrame {

    /**
     * Creates new form Users
     * 
     */
    Connection con=null;
    PreparedStatement st=null;
    public Users() {
        initComponents();
        table();
    }
    
         public void clear(){
         
         Name.setText("");
         Email.setText("");
         Phone.setText("");
         Designation.setText("");
         //Department.setText("");
         //Combo.setToolTipText("");
         Search.setText("");
         Password.setText("");
     }
    
         public void table(){
       // DefaultTableModel dtm(DefaultTableModel) jTable1.getModel();
        //dtm.setRowCount(0)
        try {
           String url="jdbc:mysql://localhost:3306/Procrument";
           String usname="root";
           String pass="Asad2526?";
           Connection con=DriverManager.getConnection(url,usname,pass);
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("Select * from users");
        DefaultTableModel tb =(DefaultTableModel) jTable1.getModel();
        tb.setRowCount(0);
        while(rs.next()){
           
            tb.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),
            rs.getString(5),rs.getString(6),rs.getString(7)});
            
        }          
        }
        catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Search = new java.awt.TextField();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Email = new java.awt.TextField();
        Phone = new java.awt.TextField();
        Designation = new java.awt.TextField();
        Password = new javax.swing.JPasswordField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        Name = new java.awt.TextField();
        button5 = new java.awt.Button();
        Combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(220, 275));
        setUndecorated(true);

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "user_id", "Name", "Email", "Phone", "Designation", "Department"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 670, 430));

        Search.setBackground(new java.awt.Color(51, 51, 51));
        Search.setForeground(new java.awt.Color(255, 255, 255));
        panel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 150, 30));

        panel2.setBackground(new java.awt.Color(51, 51, 51));
        panel2.setForeground(new java.awt.Color(255, 255, 255));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Information");
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 150, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone");
        panel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Designation");
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Deparment");
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 20));

        Email.setBackground(new java.awt.Color(51, 51, 51));
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        panel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, 20));

        Phone.setBackground(new java.awt.Color(51, 51, 51));
        Phone.setForeground(new java.awt.Color(255, 255, 255));
        panel2.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 160, 20));

        Designation.setBackground(new java.awt.Color(51, 51, 51));
        Designation.setForeground(new java.awt.Color(255, 255, 255));
        panel2.add(Designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 160, 20));

        Password.setBackground(new java.awt.Color(51, 51, 51));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        panel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 160, -1));

        button1.setBackground(new java.awt.Color(255, 0, 51));
        button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(0, 0, 0));
        button1.setLabel("Clear");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel2.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 394, 360, 30));

        button2.setBackground(new java.awt.Color(255, 255, 0));
        button2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button2.setForeground(new java.awt.Color(0, 0, 0));
        button2.setLabel("Add");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panel2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 344, 100, 30));

        button3.setBackground(new java.awt.Color(0, 255, 0));
        button3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button3.setForeground(new java.awt.Color(0, 0, 0));
        button3.setLabel("Edit");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panel2.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 344, 90, 30));

        Name.setBackground(new java.awt.Color(51, 51, 51));
        Name.setForeground(new java.awt.Color(255, 255, 255));
        panel2.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 160, 20));

        button5.setBackground(new java.awt.Color(255, 0, 0));
        button5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button5.setForeground(new java.awt.Color(0, 0, 0));
        button5.setLabel("Delete");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        panel2.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 344, 90, 30));

        Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BBA", "Computer Science", "Accounting", "Electricial", "Education" }));
        panel2.add(Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 160, -1));

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 360, 430));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Information");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 300, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/procurement_management/project/Icons/search.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
         try {
             
           String url="jdbc:mysql://localhost:3306/Procrument";
           String usname="root";
           String pass="Asad2526?";
           Connection con=DriverManager.getConnection(url,usname,pass);
                    if(Name.getText().equals("")){
                   JOptionPane.showMessageDialog(null, "Name cant be nulll"); 
                   clear();
                   return;
                }
                 

                 if(Email.getText().equals("")){
                   JOptionPane.showMessageDialog(null, "Please Enter correct Email"); 
                   clear();
                   return;
                }
                 if(Phone.getText().equals("")){
                   JOptionPane.showMessageDialog(null, "Phone number cant be null");
                   clear();
                   return;
                }
               
                 if(Designation.getText().equals("")){
                   JOptionPane.showMessageDialog(null, "Designation can not be null");
                   clear();
                   return;
                }
                 
                   if(Password.getText().equals("")){
                   JOptionPane.showMessageDialog(null, "Password can not be null");
                   clear();
                   return;
                }
        String query="Insert into users(Name,Mail,Phone,Designation,Department,Passwd) values (?,?,?,?,?,?)";
        //String query=INSERT INTO registration  VALUES(?,?,?,?,?,?,?,?,?,?);
        st=con.prepareStatement(query);

       // st.setString(1, EmpCode.getText());
        //st.setString(2,EmpCode.getText());
        st.setString(1, Name.getText());
        st.setString(2,Email.getText());
        st.setString(3,Phone.getText());
        st.setString(4, Designation.getText());
        
        st.setString(5, (String) Combo.getSelectedItem());
        st.setString(6,Password.getText());

        st.executeUpdate();
        
         JOptionPane.showMessageDialog(null, "Account Resgistred registerd sucessfully ");
         
         clear();
         table();
      
        }
        
        catch(Exception e){
            
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
           try {
           String url="jdbc:mysql://localhost:3306/Procrument";
           String usname="root";
           String pass="Asad2526?";
           String search=Search.getText();
           Connection con=DriverManager.getConnection(url,usname,pass);
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("Select * from users where userid='"+search+"'");
        
       int i=0;
        while(rs.next()){
           i=1;
           break;
          
        } 
        if(i==0){
               JOptionPane.showMessageDialog(null, "user does not Exit ");
               clear();
               return;
           }
         
         st.execute("update users set Name='"+Name.getText()+"',Mail='"+Email.getText()+"',Phone='"+Phone.getText()+"',Designation='"+Designation.getText()+"',Department='"+(String) Combo.getSelectedItem()+"',Passwd='"+Password.getText()+"' where userid='"+search+"'");
         JOptionPane.showMessageDialog(null,"Updated Successfully ");
         clear();
         table();
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_button1ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
         if(jTable1.getSelectedRow()!=-1){
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            try {
           String url="jdbc:mysql://localhost:3306/Procrument";
           String usname="root";
           String pass="Asad2526?";
           Connection con=DriverManager.getConnection(url,usname,pass);
            Statement st=con.createStatement();
                 int row = jTable1.getSelectedRow();
                 String eve = jTable1.getValueAt(row, 0).toString();
                 st.executeUpdate("Delete from users where userid='"+eve+"'");
                 JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
                 table();
         }
         
         catch(Exception e ){
             
         }
           } 
           else{
               JOptionPane.showMessageDialog(null, "Please Select any row");
           }
    }//GEN-LAST:event_button5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                 try {
           String url="jdbc:mysql://localhost:3306/Procrument";
           String usname="root";
           String pass="Asad2526?";
           String search=Search.getText();
           Connection con=DriverManager.getConnection(url,usname,pass);
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("Select * from users where userid='"+search+"'");
        
       int i=0;
        while(rs.next()){
           i=1;
          
           Name.setText(rs.getString(2));
           Email.setText(rs.getString(3));
           Phone.setText(rs.getString(4));
           Designation.setText(rs.getString(5));
          // combo.setText(rs.getString(6));
          
           Password.setText(rs.getString(7));
           
            
           
            
        } 
        if(i==0){
               JOptionPane.showMessageDialog(null, "user does not Exit ");
               clear();
           }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo;
    private java.awt.TextField Designation;
    private java.awt.TextField Email;
    private java.awt.TextField Name;
    private javax.swing.JPasswordField Password;
    private java.awt.TextField Phone;
    private java.awt.TextField Search;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
